### ISSUE TITLE
BedWars Bug

### ISSUE THREAD

**Issue by awhdenjz** [SpiceX/BedWars_v1_fixed#1]
#0 pmsrc/src/pocketmine/entity/Entity(381): pocketmine\entity\Entity->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
#1 pmsrc/src/pocketmine/level/Level(1674): pocketmine\entity\Entity::createEntity(string[4] Item, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
#2 plugins/BedWars_v1_fixed-master/src/BedWars/game/Generator(125): pocketmine\level\Level->dropItem(object pocketmine\math\Vector3, object pocketmine\item\Item)
#3 plugins/BedWars_v1_fixed-master/src/BedWars/game/Game(558): BedWars\game\Generator->tick()
#4 plugins/BedWars_v1_fixed-master/src/BedWars/game/GameTick(24): BedWars\game\Game->tick()
#5 pmsrc/src/pocketmine/scheduler/TaskHandler(137): BedWars\game\GameTick->onRun(integer 3381)
#6 pmsrc/src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 3381)
#7 pmsrc/src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 3381)
#8 pmsrc/src/pocketmine/Server(2389): pocketmine\plugin\PluginManager->tickSchedulers(integer 3381)
#9 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
#10 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
#11 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
#12 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#13 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
#14 pmsrc(11): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

**Comment by SpiceX** [comment]
no
